spring:
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stoplist.c3qsy2eywn3l.ap-northeast-2.rds.amazonaws.com:3306/stoplist?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: SpringBoot97!!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC